### ISSUE TITLE
why nothing left?

### ISSUE THREAD

**Issue by mmsamiei** [1995parham/1995parham.github.io#4]

**Comment by 1995parham** [comment]
Because everyone who I know is left me behind, and I have no one left. When you have no one left, then your solution space is empty, and you cannot even think about finding an answer.

**Comment by mmsamiei** [comment]
dear Parham, I sympathize with you well. Like you, I am in a similar situation. I have missed many of my friends. not only who went to a foreign country but also who got married or want to get married. today I asked my friend that if he agrees to drink a cup of tea together? but he said: "sorry I hurry home in order to go to the matchmaking session!" then I became so upset and sad. Parham! you are better than me undoubtedly but I want to say something to you that maybe is effective. Loneliness can be the best friend of everyone. don't hope for others, they will leave you someday.
in the end, I wish to have your social and scientific position, you are one of the greatest person that I ever have seen in my life and have read in history stories. you are awesome, I hope you change our country and world, our legend
best wishes for you
